#!/usr/bin/bash
############ CONFIGURATION SECTION ############
LAN_IFS="ens1f1"
WAN_IFS="vlan3310 ens1f0"
BANDWIDTH="1gbit"
###############################################
TC="/sbin/tc"

for ifc in $LAN_IFS; do
  $TC qdisc del dev $ifc root
  # Qdisc - БЕЗ rate
  $TC qdisc add dev $ifc root handle 1: htb default 999 r2q 10 || true
  # Class 1:1 - С rate
  $TC class add dev $ifc parent 1: classid 1:1 htb rate ${BANDWIDTH} ceil ${BANDWIDTH} || true
  # Default class
  $TC class add dev $ifc parent 1:1 classid 1:999 htb rate ${BANDWIDTH} ceil ${BANDWIDTH} || true
done

for ifc in $WAN_IFS; do
  $TC qdisc del dev $ifc root
  $TC qdisc add dev $ifc root handle 1: htb default 999 r2q 10 || true
  $TC class add dev $ifc parent 1: classid 1:1 htb rate ${BANDWIDTH} ceil ${BANDWIDTH} || true
  $TC class add dev $ifc parent 1:1 classid 1:999 htb rate ${BANDWIDTH} ceil ${BANDWIDTH} || true
done
