#!/bin/sh

# ----------------- CONFIG -----------------
LAN_IF="vlan4001"
WAN_IF="vlan3310"
NFT_FAMILY="inet"
NFT_TABLE="firewall"
NFT_SET="allowed_clients"
NFT_MAP_U="client_mark_u"
NFT_MAP_D="client_mark_d"

# ----------------- CONFIG -----------------

LOGIN=$1
IP=$2
CASH=$4
ID=$3

SPEED=`/etc/rscriptd/GetSpeed $LOGIN`
UPSPEED=`/etc/rscriptd/GetUpSpeed $LOGIN`
MAC=`/etc/rscriptd/GetMac $LOGIN`
SCOUNT="kbit"

nft="/usr/sbin/nft"
tc="/usr/sbin/tc"

cur_date=`date \+\%Y.\%m.\%d`
cur_time=`date \+\%H:\%M:\%S`

DMARK=`expr $ID + 2`
UMARK=`expr $ID + 10001`

DMARK_HEX=$(printf "%x" $DMARK)
UMARK_HEX=$(printf "%x" $UMARK)

${tc} class add dev ${LAN_IF} parent 1:1 classid 1:${DMARK_HEX} htb rate ${SPEED}${SCOUNT}
${tc} filter add dev ${LAN_IF} parent 1: protocol ip prio 1 handle 0x${DMARK_HEX} fw classid 1:${DMARK_HEX}

${tc} class add dev ${WAN_IF} parent 1:1 classid 1:${UMARK_HEX} htb rate ${UPSPEED}${SCOUNT}
${tc} filter add dev ${WAN_IF} parent 1: protocol ip prio 1 handle 0x${UMARK_HEX} fw classid 1:${UMARK_HEX}

${nft} add element ${NFT_FAMILY} ${NFT_TABLE} ${NFT_SET} "{ $IP }"
${nft} add element ${NFT_FAMILY} ${NFT_TABLE} ${NFT_MAP_D} "{ $IP : 0x$DMARK_HEX }"
${nft} add element ${NFT_FAMILY} ${NFT_TABLE} ${NFT_MAP_U} "{ $IP : 0x$UMARK_HEX }"

# ADD TO LOG
echo "$cur_date $cur_time CONNECT: ID-$ID;LOGIN-$LOGIN;IP-$IP;CASH-$CASH;SPEED-$SPEED;UPSPEED-$UPSPEED,MAC-$MAC,DMARK-$DMARK,UMARK-$UMARK,DMARK_HEX-$DMARK_HEX,UMARK_HEX-$UMARK_HEX" >> /var/stargazer/allconnect.log
