#!/bin/sh
############ CONFIGURATION SECTION ############
# 2025.12.02 18:54:54 CONNECT: ID-2866;LOGIN-bugo6ap0_4e50;IP-10.10.165.2;CASH-0;SPEED-320000;UPSPEED-320000,MAC-64:ee:b7:fc:c4:d3,DMARK-2868,UMARK-12867,DMARK_HEX-b34,UMARK_HEX-3243
LAN_IF="vlan4001"
IFB_IF="ifb0"
NFT_FAMILY="inet"
NFT_TABLE="firewall"
NFT_SET="allowed_clients"
HASH_ROOT_IFB="2"
HASH_ROOT_LAN="1"
NFT="/sbin/nft"
TC="/sbin/tc"

#########################################################################
LOGIN=$1
IP=$2
CASH=$4
ID=$3

#########################################################################
SPEED=`/etc/rscriptd/GetSpeed $LOGIN`
UPSPEED=`/etc/rscriptd/GetUpSpeed $LOGIN`
MAC=`/etc/rscriptd/GetMac $LOGIN`
SCOUNT="kbit"

#########################################################################
cur_date=`date \+\%Y.\%m.\%d`
cur_time=`date \+\%H:\%M:\%S`

#########################################################################
# 1. Генерація ClassID
# розділяємо на DMARK і UMARK чисто для зручності пошуку, а так можуть бути однакові, так як фільтри створюються на різних інтерфейсах
DMARK=`expr $ID + 2`
UMARK=`expr $ID + 10001`

DMARK_HEX=$(printf "%x" $DMARK)
UMARK_HEX=$(printf "%x" $UMARK)

#########################################################################
# 2. Генерація Filter Handle (Для u32 фільтра - МАКСИМУМ 0xFFF!)
# Беремо ID користувача і накладаємо маску 0xFFF (4095).
# Це гарантує, що хендл завжди валідний для u32.
# Прикалад: IP 10.10.165.2 -> O3=165, O4=2 -> Hex a502
FILTER_ID=$(((ID + 1) & 4095))
FILTER_ID_HEX=$(printf "%x" $FILTER_ID)

O3=$(echo $IP | awk -F . '{print $3}')
O4=$(echo $IP | awk -F . '{print $4}')

TABLE_ID=$(printf "%02x" $((O3+1)))
BUCKET_HEX=$(printf "%x" $O4)

#########################################################################
# 4. ФОРМУВАННЯ ПОВНОГО HANDLE (Таблиця:Кошик:ID)
FULL_HANDLE_FILTER="${TABLE_ID}:${BUCKET_HEX}:${FILTER_ID_HEX}"

#########################################################################
# 3. ДИНАМИЧЕСКИЙ РАСЧЕТ BURST (ls m1)
#########################################################################
# Целевое время кредита: 50 миллисекунд (0.05s)
TIME_MS=50

# Вычисляем константы заранее через арифметическое расширение $((...))
# 64 KB
MIN_BURST_BYTES=$((64 * 1024))
# 6 MB
MAX_BURST_BYTES=$((6 * 1024 * 1024))

calculate_burst() {
    # В sh аргументы принимаем в переменные.    
    _spd_kbit="$1"
    _burst_res=1680
    
    # Формула: (Speed_Kbit * Time_Ms) / 8
    _burst_res=$(( (_spd_kbit * TIME_MS) / 8 ))
    
    # Проверка МИНИМУМА
    if [ "$_burst_res" -lt "$MIN_BURST_BYTES" ]; then
        _burst_res="$MIN_BURST_BYTES"
    fi
    
    # Проверка МАКСИМУМА
    if [ "$_burst_res" -gt "$MAX_BURST_BYTES" ]; then
        _burst_res="$MAX_BURST_BYTES"
    fi
    
    echo "$_burst_res"
}

BURST_D=$(calculate_burst $SPEED)
BURST_U=$(calculate_burst $UPSPEED)

#####################################################################
# 1. DOWNLOAD (LAN Interface)
#####################################################################
# Створюємо клас 
$TC class add dev ${LAN_IF} parent ${HASH_ROOT_LAN}:0 classid ${HASH_ROOT_LAN}:${DMARK_HEX} htb \
    rate ${SPEED}${SCOUNT} ceil ${SPEED}${SCOUNT} \
    burst ${BURST_D} cburst ${BURST_D} \
    quantum 65535
    
# Створюємо дочірню чергу 
$TC qdisc add dev ${LAN_IF} parent ${HASH_ROOT_LAN}:${DMARK_HEX} handle ${DMARK_HEX} fq_codel flows 1024 limit 2048

#####################################################################
# Додаємо фільтр (Тут також можна використовувати повний handle для надійності)	
#####################################################################
#tc filter add dev vlan4001 parent 1:0 protocol ip pref 3 \
#    handle a6:3:20 \
#    u32 ht a6:3: \
#    match ip dst 10.10.165.3/32 \
#    flowid 1:1000
#####################################################################
$TC filter add dev ${LAN_IF} parent ${HASH_ROOT_LAN}:0 protocol ip pref 3 \
    handle ${FULL_HANDLE_FILTER} \
    u32 ht ${TABLE_ID}:${BUCKET_HEX}: \
    match ip dst $IP/32 \
    flowid ${HASH_ROOT_LAN}:${DMARK_HEX}

#####################################################################
# 2. UPLOAD (IFB Interface)
#####################################################################
# Створюємо клас HFSC
$TC class add dev ${IFB_IF} parent ${HASH_ROOT_IFB}:0 classid ${HASH_ROOT_IFB}:${UMARK_HEX} htb \
    rate ${UPSPEED}${SCOUNT} ceil ${UPSPEED}${SCOUNT} \
    burst ${BURST_U} cburst ${BURST_U} \
    quantum 65535

# Створюємо дочірню чергу
$TC qdisc add dev ${IFB_IF} parent ${HASH_ROOT_IFB}:${UMARK_HEX} handle ${UMARK_HEX} fq_codel flows 1024 limit 2048

#####################################################################
# Додаємо фільтр (Тут також можна використовувати повний handle для надійності)
#####################################################################
$TC filter add dev ${IFB_IF} parent ${HASH_ROOT_IFB}:0 protocol ip pref 3 \
    handle ${FULL_HANDLE_FILTER} \
    u32 ht ${TABLE_ID}:${BUCKET_HEX}: \
    match ip src $IP/32 \
    flowid ${HASH_ROOT_IFB}:${UMARK_HEX}

#####################################################################
# 3. FIREWALL
#####################################################################
${NFT} add element ${NFT_FAMILY} ${NFT_TABLE} ${NFT_SET} "{ $IP }"

# ADD TO LOG
echo "$cur_date $cur_time CONNECT: ID-$ID;LOGIN-$LOGIN;IP-$IP;CASH-$CASH;SPEED-$SPEED;UPSPEED-$UPSPEED,MAC-$MAC,DMARK-$DMARK,UMARK-$UMARK,DMARK_HEX-$DMARK_HEX,UMARK_HEX-$UMARK_HEX" >> /var/stargazer/allconnect.log
